"""Build the revised, paginated SEDAR project reference. Run from project root."""
from pathlib import Path
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.graphics.shapes import Drawing, Rect, Circle, Line, String, Polygon

OUT = Path('public/SEDAR-reference.pdf')
GREEN = colors.HexColor('#285b4e')
INK = colors.HexColor('#263e39')
PALE = colors.HexColor('#edf4ef')
GRAY = colors.HexColor('#657970')
styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='BodySEDAR',fontName='Helvetica',fontSize=10,leading=15,textColor=INK,spaceAfter=10))
styles.add(ParagraphStyle(name='TitleSEDAR',fontName='Helvetica-Bold',fontSize=30,leading=35,textColor=GREEN,spaceAfter=14))
styles.add(ParagraphStyle(name='SubSEDAR',fontName='Helvetica-Bold',fontSize=17,leading=23,textColor=GREEN,spaceAfter=12))
styles.add(ParagraphStyle(name='SmallSEDAR',fontName='Helvetica',fontSize=8.5,leading=12,textColor=GRAY,spaceAfter=7))
styles.add(ParagraphStyle(name='TableSEDAR',fontName='Helvetica',fontSize=9,leading=13,textColor=INK))
story=[]
def p(text,style='BodySEDAR'): return Paragraph(text,styles[style])
def add(text,style='BodySEDAR'): story.append(p(text,style))
def title(n,text): add('SEDAR / PROJECT REFERENCE / REVISION 02','SmallSEDAR');add(f'{n:02d}  {text}','TitleSEDAR')
def sub(text): add(text,'SubSEDAR')
def table(rows,widths):
 t=Table([[p(str(c),'TableSEDAR') for c in row] for row in rows],colWidths=widths,hAlign='LEFT',repeatRows=1)
 t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),PALE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),9),('RIGHTPADDING',(0,0),(-1,-1),9),('TOPPADDING',(0,0),(-1,-1),9),('BOTTOMPADDING',(0,0),(-1,-1),9),('LINEBELOW',(0,0),(-1,-1),.4,colors.HexColor('#d4e1d8'))]))
 story.append(t);story.append(Spacer(1,13))
def page():story.append(PageBreak())
def footer(c,doc):
 c.setStrokeColor(colors.HexColor('#d4e1d8'));c.line(45,42,550,42);c.setFillColor(GRAY);c.setFont('Helvetica',8);c.drawString(45,29,'SEDAR | Four-spring active-response prototype | 19 September 2026');c.drawRightString(550,29,str(doc.page))

title(1,'The corrected concept')
add('<b>Seismic Eddy Current and Active Damping Response</b>')
add('An educational model that connects a moving ground base, four spring supports, a building platform, a roof-mounted motion sensor and two independently switched solenoids. This revision follows the clarified mechanical layout and the relay-based circuit supplied with the project.')
sub('What is fixed, and what moves?')
table([['Part','Arrangement and purpose'],['Ground base','The earthquake input. Four corner bolts are fixed to this base. There are no separate tall pillars.'],['Four springs','One longer spring at each corner, seated over a base-fixed screw with 1/2 inch (12.7 mm) inserted into the spring. Together they carry the upper platform.'],['Building platform','Rests on all four springs and carries the model building. It can move relative to the base.'],['Solenoid 01','Between spring S1 and S2. Centered compact push-pull unit; illustrated plunger moves left toward S1 on energization.'],['Solenoid 02','Between spring S3 and S4. Centered mirrored push-pull unit; illustrated plunger moves right toward S4 on energization.'],['MPU6050','Fixed to the roof of the building. Reads building acceleration and angular motion.']],[120,385])
sub('The essential correction')
add('The solenoid rods act on the <b>springs</b>, not directly on the building. The spring reaction is transmitted through the spring seats into the moving platform. The previous eight-spring illustration and freestanding side pillars are superseded.')
add('<b>Confirmed by the project owner:</b> four springs, a base-fixed screw inserted 1/2 inch into each longer spring, two mirrored compact push-pull solenoids between the spring pairs, a platform above the springs and the sensor on the roof.')
add('<b>Proposed visualization details:</b> base-fixed coil brackets and small spring-contact collars. These communicate a possible force path; they are not a finalized fabrication drawing. The 1/2-inch measurement specifies insertion depth, not screw diameter.','SmallSEDAR')
page()
title(2,'Mechanical arrangement')
add('Top view, with the building and upper platform removed. S1-S4 identify the four corner springs; they are not additional pillars.')
d=Drawing(505,228)
d.add(Rect(10,15,485,198,fillColor=PALE,strokeColor=colors.HexColor('#bdcec1'),strokeWidth=1))
for x,y,label in [(165,164,'S1'),(340,164,'S2'),(165,64,'S3'),(340,64,'S4')]:
 d.add(Circle(x,y,21,fillColor=colors.white,strokeColor=GREEN,strokeWidth=3));d.add(Circle(x,y,6,fillColor=GRAY,strokeColor=None));d.add(String(x-8,y+31,label,fontSize=11,fillColor=GREEN))
for y,number,direction in [(164,'01',-1),(64,'02',1)]:
 cx=252
 d.add(Rect(cx-30,y-17,60,34,fillColor=GREEN,strokeColor=None));d.add(String(cx-7,y-12,number,fontSize=10,fillColor=colors.white))
 d.add(Line(cx-direction*18,y,cx+direction*55,y,strokeColor=GRAY,strokeWidth=4))
 end=cx+direction*55
 d.add(Polygon([end,y,end-direction*8,y+5,end-direction*8,y-5],fillColor=colors.HexColor('#d49842'),strokeColor=None))
story.append(d);story.append(Spacer(1,12))
sub('Assembly from bottom to top')
add('<b>1.</b> Ground base, with a fixed threaded fastener at each corner.<br/><b>2.</b> Washer / retained lower spring seat around each screw; the screw enters the longer spring by 1/2 inch (12.7 mm).<br/><b>3.</b> Four springs and retained upper seats under the moving platform.<br/><b>4.</b> Upper platform, building, then roof-mounted sensor.')
add('Bolt retention, spring end retention and clearance must allow the intended lateral movement without a bolt locking the platform rigidly to the base. The model exaggerates gaps so the mechanism can be inspected; displayed dimensions are not a scale drawing.')
sub('Solenoid mounting and contact')
add('In the proposed visualization, each coil body is held to the ground base by a low saddle bracket. The short plunger protrudes from the inward side at rest. Energization slides it through the coil toward the opposite, spring-facing side. The second actuator is mirrored. The rod is not long enough to span the spring pair. A collar at the intended spring contact represents a distributed contact point rather than a sharp rod pressing on a single coil turn.')
add('The supplied photo guides the compact frame, blue winding, plunger and return spring. The coil is centered; springs are closer and the illustrated plunger slightly longer. Fit real spacing to the actual stroke. A rigid plunger translates as one piece: one end advances while the opposite retracts. Verify stroke, force, contact height and alignment on the actual unit before fabrication.')
page()
title(3,'Sensing and feedback')
sub('Why the sensor is on the roof')
add('The roof position makes building sway and rotation observable. Mount the board rigidly to the model, align and record its axes, and leave a flexible wire loop so the cable does not become an unintended spring. The MPU6050 combines a three-axis accelerometer and a three-axis gyroscope [1].')
add('A roof sensor measures the building response, not the ground motion independently. Acceleration also contains gravity effects as the structure tilts. It does not directly report displacement. Filtering, bias calibration and an appropriate motion estimate are needed; simply integrating acceleration produces drift.')
sub('Proposed operating sequence')
table([['Stage','What happens'],['1 / Initialize','Power the control circuit, check sensor communication and establish a stationary baseline. Keep both outputs inactive during startup or sensor failure.'],['2 / Detect','Read acceleration and angular rate. Filter noise and compare motion against experimentally selected thresholds.'],['3 / Estimate','Estimate the relevant motion direction. Acceleration sign alone is not the same as velocity direction.'],['4 / Select','For the illustrated X direction: a leftward spring force comes from channel 1; a rightward force comes from channel 2. Confirm this sign on the actual mechanism.'],['5 / Actuate','The selected relay closes COM to NO, energizing a 12 V solenoid. Its working rod acts on a spring contact.'],['6 / Observe','Measure the resulting response, release the actuator as required, and repeat. Use hysteresis and minimum switching intervals to avoid chatter.']],[100,405])
add('<b>Critical distinction:</b> reducing vibration requires an opposing force at the right time. Incorrect timing or mounting can add energy. The ideal web model opposes velocity; the hardware controller must be developed and tested to achieve the intended effect.')
add('The roof sensor can observe motion about multiple axes. Two push-pull actuators both aligned along X do not provide independent active control of Y and Z. Their offset positions can also introduce twisting that the simple simulator does not calculate.','SmallSEDAR')
page()
title(4,'Circuit and power paths')
add('The current design uses a two-channel relay module, not an IRF520 module. Digital output pins D8 and D9 are the project assignments. The classic Nano uses A4 for SDA and A5 for SCL [2].')
table([['Connection','Destination / function'],['Adapter +12 V','Main switch, then buck IN+ and both relay COM terminals.'],['Adapter negative','Common ground distribution point.'],['LM2596 output','Adjusted regulated 5 V to Nano 5V and relay VCC; output negative to ground.'],['MPU6050 signals','SDA to A4; SCL to A5; optional INT to D2. AD0 to ground for the default address, when appropriate.'],['Sensor supply','Use the voltage and logic levels required by the exact breakout. A module regulator does not automatically guarantee 5 V-safe I2C pins.'],['Relay inputs','IN1 to D8, IN2 to D9. Verify active-LOW or active-HIGH behavior.'],['Relay channel 1','COM to switched 12 V; NO to solenoid 01 positive. NC unused.'],['Relay channel 2','COM to switched 12 V; NO to solenoid 02 positive. NC unused.'],['Solenoid negatives','Return directly to the common ground distribution point.'],['Flyback diodes','One across each solenoid: cathode / striped end to positive, anode to negative. Select for the actual coil and switching requirements.']],[145,360])
add('Keep high-current coil returns separate from the sensor and Nano return paths until the common distribution point. Verify the buck output with a meter before connecting electronics. Check relay DC inductive-load suitability and supply current against the actual solenoid specifications.')
add('The exact sensor breakout, coil current, duty cycle, stroke, force rating, spring rate, model mass and bolt dimensions have not been supplied. This reference intentionally does not invent those values.','SmallSEDAR')
page()
title(5,'Component responsibilities')
table([['Component','Quantity','Role'],['Arduino Nano','1','Reads the sensor and chooses relay states.'],['MPU6050 breakout','1','Reports acceleration and angular rate from the roof.'],['LM2596 module','1','Steps the 12 V source down to the regulated control supply.'],['12 V adapter + switch','1 each','Supplies and isolates the prototype power. Current rating must match the load.'],['Two-channel relay module','1','Independently switches each solenoid power path.'],['Push-pull solenoids','2','Apply the proposed leftward and rightward spring actions.'],['Flyback diodes','2','Provide a coil-current path when each solenoid is switched off.'],['Springs + corner anchors','4 each','Support the upper platform with compliance at all four corners.'],['Base, platform, building','1 each','Form the ground input and moving mechanical assembly.'],['Seats, brackets, contacts','As required','Retain springs and actuators while preserving intended movement.']],[151,52,302])
sub('Active actuation versus eddy-current damping')
add('The project name is retained, but the current arrangement illustrates <b>active solenoid response</b>. A powered solenoid moving a rod is not by itself proof of eddy-current damping. The original PDF described a different arrangement with a moving conductive plate and a magnetic field.')
add('A separate eddy-current stage would need a specified conductor, magnetic field geometry and relative motion. It is not included in this four-spring model. Springs store and return energy; energy reduction depends on dissipative effects and correctly timed control, not on springs alone.')
sub('Why the relay model is simplified')
add('Real relays have finite switching delays and contact life. They do not produce the continuously variable force used in the web model. Coil inductance, flyback decay, contact gaps, rod travel and return forces also affect timing. Establish a modest, measured demonstration first rather than treating ideal simulation results as hardware performance.')
page()
title(6,'Using and testing the model')
sub('The interactive website')
add('Drag the 3D model to orbit; scroll or pinch to zoom; right-drag or use two fingers to pan. Front, Side, Top and Underside buttons provide repeatable views. Top and Underside reveal the mechanism by hiding the building and upper platform. Use Show building to reassemble the view.')
add('Click the building or Trigger earthquake for ground excitation. Change intensity, compare active damping on and off, pause, or reset. The reference model at the bottom rotates independently and can be stopped. Phone input requires a motion-capable browser, permission where requested, and HTTPS.')
sub('What the graphs mean')
add('The model integrates a unit-mass spring system at 120 steps per second. Ground displacement drives spring and passive damping forces. A capped ideal force opposes building velocity. A passive comparison receives the same ground input. The reduction figure compares accumulated RMS displacements since a triggered quake or reset.')
add('Displacement is in illustrative units. The intensity slider is not a Richter magnitude. The simulation is one-axis despite its fully three-dimensional camera. It does not calculate multi-axis structural dynamics, relay delays, coil heating, force-stroke limits, torsion or contact mechanics.')
sub('Suggested prototype validation')
table([['Check','Record and compare'],['Unpowered mechanism','Verify that four springs carry the load and that the platform can move without binding, detaching or reaching unsafe travel.'],['Actuator direction','At low excitation, verify which spring the short working end contacts and the resulting platform direction. Check stroke and clearance.'],['Sensor baseline','Log stationary bias and small known movements. Record mounting axes and sampling interval.'],['Passive run','Use a repeatable ground input with the actuators disabled; measure peak response and settling time.'],['Controlled run','Repeat the same input and initial conditions with control enabled. Compare traces, contact timing and coil temperature.'],['Tuning','Adjust thresholds and timing gradually. Reject settings that increase motion or introduce twisting.']],[119,386])
add('This is a college-scale experimental prototype, not a validated earthquake-protection system for occupied buildings.','SmallSEDAR')
page()
import json
guide=json.loads(Path('src/build-guide.json').read_text(encoding='utf-8'))
for chapter, section in enumerate(guide, 7):
 title(chapter, section['title'])
 add(section['intro'])
 for idx, step in enumerate(section['steps'], 1):
  sub(f"{(chapter-7)*5+idx:02d} / {step['title']}")
  add(step['text'])
 page()
title(11,'Wiring reference and notes')
add('Original wiring image supplied with the project. Use the explicit pin table in section 04 when verifying connections; this image is a visual reference and does not specify mechanical mounting.')
story.append(Image('public/circuit.png',width=505,height=314));story.append(Spacer(1,18))
sub('Details to settle before fabrication')
add('Retain 1/2 inch (12.7 mm) screw insertion into each spring; select screw diameter and total length, spring free length, rate and retained end seats; record building mass and center of mass; confirm solenoid push/pull type, stroke, force and duty cycle; determine bracket and spring-contact geometry; verify control polarity and emergency power-off behavior.')
sub('Sources and revision history')
add('[1] TDK InvenSense, MPU-6000 / MPU-6050 Product Specification. Sensor architecture and measurement principles.<br/><link href="https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet.pdf" color="#285b4e">Official MPU-6050 product specification</link>','SmallSEDAR')
add('[2] Arduino, classic Arduino Nano product documentation. I2C pin assignment.<br/><link href="https://store.arduino.cc/collections/flying-things/products/arduino-nano" color="#285b4e">Official Arduino Nano documentation</link>','SmallSEDAR')
add('Primary project inputs: owner-supplied detailed description, wiring image, original SEDAR PDF and subsequent four-spring / compact short-stroke push-pull / 1/2-inch insertion / roof-sensor clarifications. Revision 02 replaces the earlier eight-spring website diagram. Original PDF retained separately as SEDAR-original-reference.pdf. Proposed brackets and collars are visualization assumptions, not owner-confirmed hardware.','SmallSEDAR')
SimpleDocTemplate(str(OUT),pagesize=(595.28,841.89),rightMargin=45,leftMargin=45,topMargin=42,bottomMargin=57,title='SEDAR - Four-Spring Project Reference',author='SEDAR Project').build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT.resolve())
