import {Download,FileText} from 'lucide-react';
export default function FirmwareGuide(){return <section className="firmware-guide" id="arduino-firmware">
 <span className="eyebrow">ARDUINO NANO / DOCUMENTED FIRMWARE</span><h2>Measure first. Test each actuator.</h2>
 <p>The classic Nano sketch includes sensor calibration, live readings, individual relay tests and fault shutoff. Automatic feedback is disabled by default: two delayed spring pushes can add vibration or twist the platform.</p>
 <div className="firmware-links"><a className="primary" href="https://github.com/CosmicShreyas/SEDARProject/archive/refs/heads/main.zip"><Download size={18}/>Download GitHub repository ZIP</a><a href="/SEDAR-REALITY_CHECK.md" target="_blank" rel="noreferrer"><FileText size={17}/>Read the control reality check</a><a href="/SEDAR-README.md" target="_blank" rel="noreferrer">Full upload & wiring guide</a></div>
 <details><summary>Upload and first checks</summary><ol>
 <li>Disconnect the 12 V coil branch. Extract the ZIP and open <code>SEDARProject-main/firmware/SEDAR_Nano/SEDAR_Nano.ino</code> in Arduino IDE.</li>
 <li>Install Arduino AVR Boards 1.8.6 or later. Select <strong>Arduino Nano → ATmega328P</strong> and your port. Some clones require <strong>Old Bootloader</strong>.</li>
 <li>Verify the relay module’s active-LOW/active-HIGH setting in the sketch. Upload, then open Serial Monitor at <strong>115200 baud / Newline</strong>.</li>
 <li>Keep the roof sensor flat, +Z upward, and still for four seconds. Send <code>CALIBRATE</code> (or <code>CAL</code>) for a fresh resting baseline; wait for the progress messages and <code>CAL OK</code>. Use <code>STATUS</code> and <code>STREAM ON</code> to inspect readings.</li>
 <li>With coil power still disconnected, use <code>TEST1</code> and <code>TEST2</code> to check relay polarity and COM/NO operation. Each requests a brief pulse. Confirm OFF at startup and after <code>STOP</code>.</li>
 <li>Only after checking component ratings and wiring, test one powered solenoid at a time. Observe platform force, contact, release and twisting. Follow the included commissioning guide.</li>
 </ol><p><code>ARM</code> is deliberately locked in the default build. The experimental option requires measured hardware checks; enabling it does not establish stable damping. The code compiles for the classic Nano but has not been tested on your mechanism.</p></details>
 <details><summary>Research and improved pulse logic</summary><p>The experimental controller now uses calibration-based noise thresholds, direction confirmation, one pulse per confirmed half-cycle, reversal prediction with assumed actuator delays, and horizontal-only motion control. These deliberately skip uncertain pulses. Actual contact and release timing still need measurement.</p><a href="/SEDAR-CONTROL_RESEARCH.md" target="_blank" rel="noreferrer">Read the research, assumptions and software tests</a></details>
 <details><summary>Why can the solenoids add shake?</summary><p>A pulse can begin against the movement and continue after the platform reverses. Relay switching, coil-current decay and rod return take time. A roof accelerometer does not directly measure motion relative to the base, and filtered velocity can lag.</p><p>In the two-row arrangement, opposite forces at opposite offsets can both twist the platform in the same direction. Spring contact also stores energy that can rebound. Short pulses and software limits help control commands; they do not prove that the mechanism removes energy.</p></details>
 </section>}
