import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowUpRight,RotateCcw,Play,Pause,Smartphone,ChevronDown,MoveHorizontal,ShieldCheck,Cpu,Radio,Zap,BookOpen,X,ExternalLink} from 'lucide-react';
import {initialState,step} from './physics';
import './styles.css';
import Model3D from './Model3D';
import BuildGuide from './BuildGuide';

function Chart({samples}){const path=(key)=>samples.map((p,i)=>`${i?'L':'M'}${i*600/239},${60-p[key]*.65}`).join(' ');return <svg viewBox="0 0 600 120" className="chart" role="img" aria-label="Last 12 seconds of ground and building displacement"><path d="M0 20H600M0 60H600M0 100H600" stroke="#e5eae7" strokeDasharray="4 4"/><path d={path('ground')} fill="none" stroke="#c79666" strokeWidth="1.5"/><path d={path('x')} fill="none" stroke="#22716a" strokeWidth="2.5"/></svg>}
function App(){const sim=useRef(initialState()),config=useRef({strength:55,damping:true}),motion=useRef(0),motionCleanup=useRef(null);const [s,setS]=useState({...sim.current}),[strength,setStrength]=useState(55),[damping,setDamping]=useState(true),[paused,setPaused]=useState(false),[labels,setLabels]=useState(true),[phone,setPhone]=useState(false),[phoneStatus,setPhoneStatus]=useState(''),[tab,setTab]=useState('simulation'),[circuit,setCircuit]=useState(false);const phase=s.remaining>0?'Earthquake in progress':Math.abs(s.v)+Math.abs(s.x)>.8?'Settling':'System stable';
 useEffect(()=>{config.current={strength,damping}},[strength,damping]);
 useEffect(()=>{let raf,prev=0,acc=0,sample=0,paint=0;function loop(now){if(!prev)prev=now;const elapsed=Math.min((now-prev)/1000,.05);prev=now;if(!paused){acc+=elapsed;while(acc>=1/120){step(sim.current,1/120,{...config.current,input:motion.current});motion.current*=.995;acc-=1/120;}sample+=elapsed;paint+=elapsed;if(sample>=.05){sample=0;sim.current.samples.push({ground:sim.current.ground,x:sim.current.x});if(sim.current.samples.length>240)sim.current.samples.shift();}if(paint>=1/30){paint=0;setS({...sim.current,samples:[...sim.current.samples]});}}raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[paused]);
 useEffect(()=>()=>motionCleanup.current?.(),[]);
 useEffect(()=>{if(!circuit)return;const cb=e=>{if(e.key==='Escape')setCircuit(false)};window.addEventListener('keydown',cb);return()=>window.removeEventListener('keydown',cb)},[circuit]);
 function quake(){sim.current.remaining=6;sim.current.elapsed=0;sim.current.energy=0;sim.current.passiveEnergy=0;setPaused(false)}
 function reset(){sim.current=initialState();motion.current=0;setS({...sim.current});setPaused(false)}
 async function enablePhone(){if(phone){motionCleanup.current?.();setPhone(false);setPhoneStatus('Phone motion disconnected.');return}if(!window.isSecureContext){setPhoneStatus('Phone motion needs HTTPS. Open the published site on your phone.');return}if(!window.DeviceMotionEvent){setPhoneStatus('Motion sensors are unavailable here. Use the earthquake button instead.');return}try{if(typeof DeviceMotionEvent.requestPermission==='function'){const p=await DeviceMotionEvent.requestPermission();if(p!=='granted'){setPhoneStatus('Motion access was declined. You can still use the earthquake button.');return}}let received=false,last=0,baseline=0;const handler=e=>{const a=e.acceleration?.x;const raw=e.accelerationIncludingGravity?.x;if(a==null&&raw==null)return;received=true;baseline=.9*baseline+.1*(raw??0);const value=a??((raw??0)-baseline);if(Math.abs(value)>.35){motion.current=Math.max(-30,Math.min(30,value*3));if(Date.now()-last>300){setPhoneStatus('Motion detected — gently shake left and right.');last=Date.now()}}};window.addEventListener('devicemotion',handler);const timeout=setTimeout(()=>{if(!received)setPhoneStatus('No sensor readings yet. Check browser motion access, or use the earthquake button.');},4000);motionCleanup.current=()=>{window.removeEventListener('devicemotion',handler);clearTimeout(timeout);motion.current=0};setPhone(true);setPaused(false);setPhoneStatus('Connected. Gently move your phone left and right.');}catch{setPhoneStatus('Could not access motion sensors. Use the earthquake button instead.')}}
 const reduction=s.passiveEnergy>.5?Math.max(0,Math.min(100,100*(1-Math.sqrt(s.energy/s.passiveEnergy)))):0;
 return <><header><a className="brand" href="#"><span className="brand-icon"><Activity size={25}/></span>SEDAR<span className="brand-divider"/><span className="brand-caption">SEISMIC RESPONSE LAB</span></a><a className="project-link" href="/SEDAR-reference.pdf" target="_blank" rel="noreferrer"><BookOpen size={16}/>Project reference<ArrowUpRight size={15}/></a></header>
 <main><div className="intro"><div><div className="eyebrow text-teal-700">INTERACTIVE ENGINEERING EXPLORER</div><h1>A little motion.<br className="mobile-break"/> A smarter response.</h1><p>Explore how SEDAR senses movement and helps a model building find its balance.</p></div><div className="prototype"><span className="dot"/>EDUCATIONAL PROTOTYPE<span>Seismic Eddy Current and Active Damping Response</span></div></div>
 <nav className="tabs" aria-label="Project views"><button onClick={()=>setTab('simulation')} className={tab==='simulation'?'selected':''}><Activity size={17}/>Live simulation</button><button onClick={()=>setTab('system')} className={tab==='system'?'selected':''}><Cpu size={17}/>Inside the system</button><button onClick={()=>setTab('build')} className={tab==='build'?'selected':''}><BookOpen size={17}/>Build guide</button><span>MODEL 01 <span>/</span> ACTIVE DAMPING</span></nav>
 {tab==='build'?<BuildGuide/>:tab==='simulation'?<><div className="lab-grid"><section className="model-panel"><div className="panel-heading"><div><span className="section-number">01</span><h2>The shake table</h2></div><span className={`status ${phase==='System stable'?'stable':''}`}><span className="dot"/>{paused?'Simulation paused':phase}</span></div><Model3D s={s} onQuake={quake} labels={labels}/><div className="model-footer"><label><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/> Show component labels</label><span>360° inspection · X-axis damping</span></div></section>
 <aside className="controls"><div className="panel-heading"><div><span className="section-number">02</span><h2>Experiment controls</h2></div></div><div className="control-content"><label className="range-label" htmlFor="intensity">Earthquake intensity <span>{strength<35?'Gentle':strength<75?'Moderate':'Strong'}</span></label><input id="intensity" type="range" min="15" max="100" value={strength} onChange={e=>setStrength(+e.target.value)}/><div className="range-ends"><span>Gentle</span><span>Strong</span></div><button className="primary" onClick={quake}><Activity size={19}/>Trigger earthquake<ArrowUpRight size={18}/></button><div className="secondary-buttons"><button onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>} {paused?'Resume':'Pause'}</button><button onClick={reset}><RotateCcw size={16}/>Reset</button></div><div className="damping-row"><div><strong>Active damping</strong><p>Let the solenoids respond</p></div><button className={`switch ${damping?'on':''}`} role="switch" aria-checked={damping} aria-label="Active damping" onClick={()=>setDamping(!damping)}><span/></button></div><div className="actuator-cards">{['01 · pushes left','02 · pushes right'].map((name,i)=>{const active=i===0?s.force< -12:s.force>12;return <div key={name} className={active?'energized':''}><span>{name}</span><strong><span className={`dot ${active?'':'muted'}`}/>{active?'Energized':'Standby'}</strong><small>CH {i+1} · 12 V</small></div>})}</div><button className={`phone ${phone?'connected':''}`} onClick={enablePhone}><Smartphone size={20}/><span>{phone?'Disconnect phone motion':'Use your phone’s motion'}<small>{phone?'Motion input enabled':'Shake your phone to move the base'}</small></span><ArrowUpRight size={16}/></button>{phoneStatus&&<p className="phone-message" role="status">{phoneStatus}</p>}</div></aside></div>
 <div className="readouts"><section className="trace-panel"><div className="trace-header"><h2>Motion, in real time</h2><div className="legend"><span><i/>Ground</span><span><i/>Building</span></div></div><Chart samples={s.samples}/><div className="chart-footer"><span>Displacement · model units</span><span>12-second rolling window</span></div></section><section className="metric"><span className="metric-icon"><MoveHorizontal size={20}/></span><p>Building displacement</p><strong>{Math.abs(s.x).toFixed(1)}<small> u</small></strong><span>From the resting position</span></section><section className="metric"><span className="metric-icon"><ShieldCheck size={20}/></span><p>Motion reduction</p><strong>{s.passiveEnergy>.5?Math.round(reduction):'—'}<small>{s.passiveEnergy>.5?' %':''}</small></strong><span>RMS vs. a passive spring model</span></section></div>
 <section className="explanation"><div><span className="eyebrow">THE FEEDBACK LOOP</span><h2>Sense. Respond. Stabilize.</h2><p>Movement becomes a signal. A signal becomes an opposing force.</p></div><div className="flow"><div><Radio/><strong>01 / Detect</strong><span>MPU6050 reads motion</span></div><b>→</b><div><Cpu/><strong>02 / Decide</strong><span>Arduino selects a channel</span></div><b>→</b><div><Zap/><strong>03 / Dampen</strong><span>Rods act on the springs</span></div></div><button onClick={()=>setTab('system')}>Explore the circuit<ArrowUpRight size={16}/></button></section></>:<section className="system-view"><div className="system-copy"><span className="eyebrow">FROM MOVEMENT TO RESPONSE</span><h2>Small components.<br/>A continuous feedback loop.</h2><p>The roof-mounted MPU6050 measures the model’s movement. The Nano evaluates the signal, then switches either 12 V solenoid through a two-channel relay.</p><button className="primary" onClick={()=>setCircuit(true)}>Inspect wiring diagram<ExternalLink size={17}/></button><p className="note">This explorer follows the relay-based circuit and your detailed project description. The revised PDF explains the four-spring mechanism, through-rods, roof sensor, power paths and feedback loop. The original PDF described an earlier MOSFET / eddy-current concept.</p></div><button className="circuit-preview" onClick={()=>setCircuit(true)} aria-label="Enlarge supplied circuit diagram"><img src="/circuit.png" alt="Supplied SEDAR wiring diagram with power adapter, buck converter, Arduino Nano, MPU6050, relay and two solenoids"/></button><div className="component-list">{[['MPU6050','Sense movement','SDA → A4 · SCL → A5 · optional INT → D2'],['Arduino Nano','Process the response','5 V regulated supply · shared ground'],['Two-channel relay','Switch each actuator','IN1 → D8 · IN2 → D9 · COM / NO contacts'],['2 × 12 V solenoids','Apply opposing forces','Compact mirrored push-pull plungers between each spring pair; short stroke.'],['LM2596 converter','Power the electronics','12 V input → regulated 5 V output'],['Four corner springs','Carry the building platform','Four longer springs; each base-fixed screw enters its spring by 1/2 inch']].map(([name,role,detail],i)=><article key={name}><span className="section-number">0{i+1}</span><h3>{name}</h3><strong>{role}</strong><p>{detail}</p></article>)}</div></section>}
 <section className="reference-section"><div className="reference-heading"><div><span className="eyebrow">FOUR CORNERS. ONE MOVING PLATFORM.</span><h2>The mechanism, from every angle.</h2><p>Each longer spring fits over a base-fixed screw with 1/2 inch (12.7 mm) of insertion. The platform rests on the four springs; the solenoid rods act on the springs beneath it.</p></div><a href="/SEDAR-reference.pdf" target="_blank" rel="noreferrer">Read the updated reference <ArrowUpRight size={16}/></a></div><div className="reference-grid"><Model3D reference labels/><div className="mechanism-notes"><span className="eyebrow">TOP VIEW / PLATFORM REMOVED</span><div className="layout-row"><span>S1</span><strong>← Solenoid 01</strong><span>S2</span></div><div className="layout-row"><span>S3</span><strong>Solenoid 02 →</strong><span>S4</span></div><h3>The force goes into the spring.</h3><p>The coil bodies are shown fastened to the base between each pair of springs. Each short plunger protrudes inward at rest, then slides through the coil toward its spring when energized. The second unit is mirrored. These are compact push-pull solenoids, not long rods joining two springs.</p><p>Each coil is centered between a closer pair of springs, with a slightly longer illustrated plunger. Spring spacing, plunger length, contact collars and brackets must be matched to the actual actuator stroke. Your four springs carry the platform; there are no additional support pillars.</p><p className="note">The 3D camera can inspect every side. The current two-actuator model demonstrates left–right control only; it does not imply independent control of all three axes. The screw insertion is 1/2 inch (12.7 mm); other dimensions are illustrative.</p></div></div></section>
 <footer><span className="footer-brand">SEDAR <span>/ BUILT TO UNDERSTAND MOTION</span></span><p>Educational simulation. Idealized forces and model units; not measured hardware performance or a structural safety prediction.</p></footer>
 </main>{circuit&&<div className="modal" role="dialog" aria-modal="true" aria-label="Supplied circuit diagram" onClick={()=>setCircuit(false)}><div onClick={e=>e.stopPropagation()}><button autoFocus aria-label="Close circuit diagram" onClick={()=>setCircuit(false)}><X/></button><img src="/circuit.png" alt="Full supplied SEDAR circuit diagram"/><p>Reference wiring supplied with the project. Pin assignments follow the detailed project description.</p></div></div>}</>}
createRoot(document.getElementById('root')).render(<App/>);
